export default {
  light: {
    primary: "#444",
    secondary: "#888",
    background: "#fff",
    tint: "teal",
    tabIconDefault: "#8aa",
    tabIconSelected: "#fff",
    overlay: "#888",
    warning: "red",
    border: "#ccc",
    text: "#000",
  },
  dark: {
    primary: "#444",
    secondary: "#888",
    background: "#fff",
    tint: "teal",
    tabIconDefault: "#8aa",
    tabIconSelected: "#fff",
    overlay: "#888",
    warning: "red",
    border: "#ccc",
    text: "#000",
  },
};
